// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// prox_sorted_L1_C
NumericVector prox_sorted_L1_C(NumericVector y, NumericVector lambda, IntegerVector order);
RcppExport SEXP _glmSlope_prox_sorted_L1_C(SEXP ySEXP, SEXP lambdaSEXP, SEXP orderSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type order(orderSEXP);
    rcpp_result_gen = Rcpp::wrap(prox_sorted_L1_C(y, lambda, order));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_glmSlope_prox_sorted_L1_C", (DL_FUNC) &_glmSlope_prox_sorted_L1_C, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_glmSlope(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
